name = "Nevanlinna"
uuid = "0b21cfa8-e591-48a4-a07b-a9d20be7c264"
authors = ["Kosuke Nogaki <nogaki.kosuke.83v@st.kyoto-u.ac.jp>, Jiani Fei <jianif@stanford.edu>, Emanuel Gull <egull@umich.edu>, Hiroshi Shinaoka <h.shinaoka@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultiFloats = "bdf0d083-296b-4888-a5b6-7498122e68a5"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SparseIR = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1"
SparseIR = "^0.97.0, 1"
MultiFloats = "^1.0.0"
Optim = "^1.7.0"
Zygote = "^0.6.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
